# Generated by Django 4.0.1 on 2022-02-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_alter_runway_runway_designation'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_origin', to='airports.airport'),
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=255)),
                ('airline_code', models.CharField(max_length=2)),
                ('origin_air', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airline_origin', to='flights.flight')),
            ],
        ),
    ]
