# Generated by Django 4.0.1 on 2022-02-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_origin_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
