# Generated by Django 4.0.1 on 2022-02-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='origin_air',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='airline', to='flights.airline'),
            preserve_default=False,
        ),
    ]
