# Generated by Django 4.0.1 on 2022-02-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_class',
            field=models.CharField(choices=[('F', 'First Class'), ('B', 'Business Class'), ('M', 'Main Cabin')], default=None, max_length=1),
        ),
    ]
